require: rubocop-rake

inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0
  Include:
    - bin/console
    - Gemfile
    - ezclient.gemspec
    - Rakefile
    - lib/**/*
    - spec/**/*
    - gemfile/**/*
  Exclude:
    - vendor/**/*

RSpec/Rails/HaveHttpStatus:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false
