inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Include:
    - bin/console
    - Gemfile
    - ezclient.gemspec
    - Rakefile
    - lib/**/*
    - spec/**/*
    - gemfile/**/*
  Exclude:
    - vendor/**/*
    - gemfiles/**/*
