language: ruby
sudo: false
cache: bundler
before_install: gem install bundler
env: SUITE="rspec"
script: bundle exec $SUITE
matrix:
  fast_finish: true
  include:
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: ruby-head
    - rvm: 2.6
      env: SUITE="rubocop"
  allow_failures:
    - rvm: ruby-head
