language: ruby

sudo: false

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

before_install: gem install bundler

script:
  - bundle exec srb tc
  - bundle exec rake lint
  - bundle exec rake spec

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
