language: ruby

os: linux

dist: xenial

before_install: gem install bundler

jobs:
  fast_finish: true
  include:
  - rvm: 2.5
  - rvm: 2.6
  - rvm: 2.7
  - rvm: ruby-head
  allow_failures:
  - rvm: ruby-head
